-- AlterTable
ALTER TABLE `Group` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `GroupMember` MODIFY `role` VARCHAR(191) NOT NULL DEFAULT 'member';
